### PR TITLE
Added proxy

### PR DESCRIPTION
**Pull request by danmconrad**

### CODE REVIEW

**Comment by jkrems** [comment]
Could you remove bond from the test suite? Right now it's mocking a lot of stuff which makes it easy to swallow failure conditions. `bond` is actually a candidate for deletion in the next cleanup of this repo, so adding more `bond`ing will only cause more work for me next week. ;)

**Comment by danmconrad** [comment]
86'd the bond.

**Comment by jkrems** [comment]
Thanks!

**Comment by jkrems** [comment]
gofer@2.2.0

**Pull request merged**
