### PR TITLE
bumped request version to 2.57.0

### PR DESCRIPTION
**Pull request by knoma**

### CODE REVIEW

**Comment by jkrems** [comment]
Hi, thanks a lot! This seems to change an error message which break one of the tests:

```
Expected: "Invalid protocol: null"
Actually: "Invalid URI \"some-invalid/url\""
```

Other than that - LGTM!

**Comment by jkrems** [comment]
Thanks!

**Comment by jkrems** [comment]
v2.4.0

**Comment by johan** [comment]
I think something backwards-incompatible happened here – all api calls suddenly raise an exception now in a way that wasn't happening with gofer@2.3.7:

```
Error: options.baseUrl must be a string
  at Request.init (node_modules/gofer/node_modules/request/request.js:370:33)
  at new Request (node_modules/gofer/node_modules/request/request.js:265:8)
  at request (node_modules/gofer/node_modules/request/index.js:56:10)
  at EventEmitter.hub.fetch (node_modules/gofer/lib/hub.js:152:11)
  at Gofer._request (node_modules/gofer/lib/gofer.js:220:23)
  at node_modules/gofer/lib/gofer.js:156:22
```

**Comment by jkrems** [comment]
Thanks! Looking into it.

**Comment by jkrems** [comment]
Published v2.4.1 which should fix this issue. Can you confirm?

**Pull request merged**
